src/pyload/webui/app/blueprints/app_blueprint.py
# -*- coding: utf-8 -*-

import datetime
import mimetypes
import operator
import os
import re
import sys
import time
from logging import getLogger
from urllib.parse import unquote

import flask
from pyload import APPID, PKGDIR
from pyload.core.utils import format

from ..helpers import (
    clear_session, get_permission, get_redirect_url, is_authenticated, login_required, permlist, render_base,
    render_template, set_session, static_file_url)

_RE_LOGLINE = re.compile(r"\[([\d\-]+) ([\d:]+)\] +([A-Z]+) +(.+?) (.*)")

bp = flask.Blueprint("app", __name__)
log = getLogger(APPID)


@bp.route("/favicon.ico", endpoint="favicon")
def favicon():
    location = static_file_url("img/favicon.ico")
    return flask.redirect(location)


@bp.route("/render/<path:filename>", endpoint="render")
def render(filename):
    mimetype = mimetypes.guess_type(filename)[0] or "text/html"
    data = render_template(filename)
    return flask.Response(data, mimetype=mimetype)


@bp.route("/robots.txt", endpoint="robots")
def robots():
    return "User-agent: *\nDisallow: /"


# TODO: Rewrite login route using flask-login
@bp.route("/login", methods=["GET", "POST"], endpoint="login")
def login():
    api = flask.current_app.config["PYLOAD_API"]

    next_url = get_redirect_url(fallback="app.dashboard")

    if flask.request.method == "POST":
        user = flask.request.form["username"]
        password = flask.request.form["password"]
        user_info = api.check_auth(user, password)

        if flask.request.headers.get("X-Forwarded-For"):
            client_ip = flask.request.headers.get("X-Forwarded-For").split(',')[0].strip()
        else:
            client_ip = flask.request.remote_addr

        sanitized_user = user.replace("\n", "\\n").replace("\r", "\\r")
        if not user_info:
            log.error(f"Login failed for user '{sanitized_user}' [CLIENT: {client_ip}]")
            return render_template("login.html", errors=True)

        set_session(user_info)
        log.info(f"User '{sanitized_user}' successfully logged in [CLIENT: {client_ip}]")
        flask.flash("Logged in successfully")

    if is_authenticated():
        return flask.redirect(next_url)

    if api.get_config_value("webui", "autologin"):
        allusers = api.get_all_userdata()
        if len(allusers) == 1:  # TODO: check if localhost
            user_info = list(allusers.values())[0]
            set_session(user_info)
            # NOTE: Double-check authentication here because if session[name] is empty,
            #       next login_required redirects here again and all loop out.
            if is_authenticated():
                return flask.redirect(next_url)

    return render_template("login.html")


@bp.route("/logout", endpoint="logout")
def logout():
    s = flask.session
    user = s.get("name")
    clear_session(s)
    if user:
        log.info(f"User '{user}' logged out")
    return render_template("logout.html")


@bp.route("/", endpoint="index")
@bp.route("/home", endpoint="home")
@bp.route("/dashboard", endpoint="dashboard")
@login_required("LIST")
def dashboard():
    api = flask.current_app.config["PYLOAD_API"]
    links = api.status_downloads()

    for link in links:
        if link["status"] == 12:
            current_size = link["size"] - link["bleft"]
            formatted_speed = format.speed(link["speed"])
            link["info"] = f"{current_size} KiB @ {formatted_speed}"

    return render_template("dashboard.html", res=links)


@bp.route("/queue", endpoint="queue")
@login_required("LIST")
def queue():
    api = flask.current_app.config["PYLOAD_API"]
    queue = api.get_queue()
    queue.sort(key=operator.attrgetter("order"))

    return render_template("packages.html", content=queue, target=1)


@bp.route("/collector", endpoint="collector")
@login_required("LIST")
def collector():
    api = flask.current_app.config["PYLOAD_API"]
    queue = api.get_collector()

    queue.sort(key=operator.attrgetter("order"))

    return render_template("packages.html", content=queue, target=0)


@bp.route("/files", endpoint="files")
@login_required("DOWNLOAD")
def files():
    def decode_name(filename):
        try:
            return filename.decode("utf-8")
        except UnicodeDecodeError:
            return filename.decode("iso-8859-1")

    api = flask.current_app.config["PYLOAD_API"]
    root = os.fsencode(api.get_config_value("general", "storage_folder"))

    if not os.path.isdir(root):
        messages = ["Download directory not found."]
        return render_base(messages)
    data = {"folder": [], "files": []}

    for entry in sorted(os.listdir(root)):
        if os.path.isdir(os.path.join(root, entry)):
            folder = {"name": decode_name(entry), "path": decode_name(entry), "files": []}
            files = os.listdir(os.path.join(root, entry))
            for file in sorted(files):
                try:
                    if os.path.isfile(os.path.join(root, entry, file)):
                        folder["files"].append(decode_name(file))
                except Exception:
                    pass

            data["folder"].append(folder)

        elif os.path.isfile(os.path.join(root, entry)):
            data["files"].append(decode_name(entry))

    return render_template("files.html", files=data)


@bp.route("/files/get/<path:path>", endpoint="get_file")
@login_required("DOWNLOAD")
def get_file(path):
    api = flask.current_app.config["PYLOAD_API"]
    path = unquote(path).replace("..", "")
    directory = api.get_config_value("general", "storage_folder")
    return flask.send_from_directory(directory, path, as_attachment=True)


@bp.route("/settings", endpoint="settings")
@login_required("SETTINGS")
def settings():
    api = flask.current_app.config["PYLOAD_API"]
    conf = api.get_config()
    plugin = api.get_plugin_config()

    conf_menu = []
    plugin_menu = []

    for entry in sorted(conf.keys()):
        conf_menu.append((entry, conf[entry].description))

    for entry in sorted(plugin.keys()):
        plugin_menu.append((entry, plugin[entry].description))

    accs = []

    for userdata in api.get_accounts(False):
        if userdata.trafficleft is None:
            trafficleft = "not available"
        elif userdata.trafficleft == -1:
            trafficleft = "unlimited"
        elif userdata.trafficleft == 0:
            trafficleft = "drained"
        else:
            trafficleft = format.size(userdata.trafficleft)

        if userdata.validuntil == -1:
            validuntil = "unlimited"
        elif not userdata.validuntil:
            validuntil = "not available"
        else:
            t = time.localtime(userdata.validuntil)
            validuntil = time.strftime("%d.%m.%Y", t)

        if "time" in userdata.options:
            try:
                _time = userdata.options["time"][0]
            except Exception:
                _time = ""
        else:
            _time = ""

        if "limit_dl" in userdata.options:
            try:
                limitdl = userdata.options["limit_dl"][0]
            except Exception:
                limitdl = "0"
        else:
            limitdl = "0"

        accs.append(
            {
                "type": userdata.type,
                "login": userdata.login,
                "valid": userdata.valid,
                "premium": userdata.premium,
                "trafficleft": trafficleft,
                "validuntil": validuntil,
                "limitdl": limitdl,
                "time": _time,
            }
        )

    all_users = api.get_all_userdata()
    users = {}
    for userdata in all_users.values():
        name = userdata["name"]
        users[name] = {"perms": get_permission(userdata["permission"])}
        users[name]["perms"]["admin"] = userdata["role"] == 0

    admin_menu = {
        "permlist": permlist(),
        "users": users
    }

    context = {
        "conf": {"plugin": plugin_menu, "general": conf_menu, "accs": accs, "admin": admin_menu},
        "types": api.get_account_types(),
    }
    return render_template("settings.html", **context)


@bp.route("/pathchooser/", endpoint="pathchooser")
@bp.route("/filechooser/", endpoint="filechooser")
@login_required("SETTINGS")
def pathchooser():
    browse_for = "folder" if flask.request.endpoint == "app.pathchooser" else "file"
    path = os.path.normpath(flask.request.args.get('path', ""))

    if os.path.isfile(path):
        oldfile = path
        path = os.path.dirname(path)
    else:
        oldfile = ""

    abs = False

    if os.path.isdir(path):
        if os.path.isabs(path):
            cwd = os.path.realpath(path)
            abs = True
        else:
            cwd = os.path.relpath(path)
    else:
        cwd = os.getcwd()

    cwd = os.path.normpath(os.path.realpath(cwd))
    parentdir = os.path.dirname(cwd)
    if not abs:
        if os.path.realpath(cwd) == os.path.realpath("/"):
            cwd = os.path.relpath(cwd)
        else:
            cwd = os.path.relpath(cwd) + os.path.sep
        parentdir = os.path.relpath(parentdir) + os.path.sep

    if os.path.realpath(cwd) == os.path.realpath("/"):
        parentdir = ""

    try:
        folders = os.listdir(cwd)
    except Exception:
        folders = []

    files = []

    for f in folders:
        try:
            data = {"name": f, "fullpath": os.path.join(cwd, f)}
            data["sort"] = data["fullpath"].lower()
            data["modified"] = datetime.datetime.fromtimestamp(
                int(os.path.getmtime(os.path.join(cwd, f)))
            )
            data["ext"] = os.path.splitext(f)[1]
        except Exception:
            continue

        if os.path.isfile(os.path.join(cwd, f)):
            data["type"] = "file"
            data["size"] = os.path.getsize(os.path.join(cwd, f))

            power = 0
            while (data["size"] >> 10) > 0.3:
                power += 1
                data["size"] >>= 10
            units = ("", "K", "M", "G", "T")

src/pyload/webui/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/base.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/window.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='vendor/MooTools/MooDialog/css/MooDialog.css')}}"/>

<script type="text/javascript" src="{{url_for('static', filename='vendor/MooTools/MooTools-Core.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='vendor/MooTools/MooTools-More.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='vendor/MooTools/MooDialog/MooDialog.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='vendor/MooTools/MooDialog/MooDialog.Confirm.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='vendor/MooTools/Purr/purr.js')}}"></script>
<script type="text/javascript" src="{{theme_template('js/base.js')}}" nopoll={{no_status_polling}}></script>

<link rel="icon" type="image/ico" href="{{url_for('static', filename='img/favicon.ico')}}" />

<title>{% block title %}pyLoad{% endblock %}</title>

{% block head %}
{% endblock %}
</head>
<body>
<a class="anchor" name="#" id="#"></a>

<div id="head-panel">

    <div id="head-search-and-login">
    {% block headpanel %}

        {% if user.is_authenticated %}

{% if update %}
<span>
<span style="font-weight: bold; margin: 0 2px 0 2px;">{{_("pyLoad Update available!")}}</span>
</span>
{% endif %}

{% if plugins %}
<span>
<span style="font-weight: bold; margin: 0 2px 0 2px;">{{_("Plugins updated, please restart!")}}</span>
</span>
{% endif %}

<span id="cap_info" style="display: {% if captcha %}inline{%else%}none{% endif %}">
<img src="{{url_for('static', filename='img/images.png')}}" alt="Captcha:" style="vertical-align:middle; margin:2px" />
<span style="font-weight: bold; cursor: pointer; margin-right: 2px;">{{_("Captcha waiting")}}</span>
</span>

    <img src="{{url_for('static', filename='img/head-login.png')}}" alt="User:" style="vertical-align:middle; margin:2px" /><span style="padding-right: 2px;">{{user.name}}</span>
    <ul id="user-actions">
        <li><a href="{{url_for('app.logout')}}" class="action logout" rel="nofollow">{{_("Logout")}}</a></li>
        <li><a href="{{url_for('app.info')}}" class="action info" rel="nofollow">{{_("Status")}}</a></li>

    </ul>
{% else %}
    <span style="padding-right: 2px;">{{_("Please Login!")}}</span>
{% endif %}

    {% endblock %}
    </div>

    <a href="{{url_for('app.dashboard')}}"><img id="head-logo" src="{{url_for('static', filename='img/pyload-logo.png')}}" alt="pyLoad" /></a>

    <div id="head-menu">
        <ul>

        {% macro selected(name, right=False) -%}
            {% if name in url -%}class="{% if right -%}right {% endif %}selected"{%- endif %}
            {% if name not in url and right -%}class="right"{%- endif %}
        {%- endmacro %}

        {% block menu %}
        <li>
            <a href="{{url_for('app.dashboard')}}" title=""><img src="{{url_for('static', filename='img/head-menu-home.png')}}" alt="" /> {{_("Dashboard")}}</a>
        </li>
        <li {{ selected('queue') }}>
            <a href="{{url_for('app.queue')}}" title=""><img src="{{url_for('static', filename='img/head-menu-queue.png')}}" alt="" /> {{_("Queue")}}</a>
        </li>
        <li {{ selected('collector') }}>
            <a href="{{url_for('app.collector')}}" title=""><img src="{{url_for('static', filename='img/head-menu-collector.png')}}" alt="" /> {{_("Packages")}}</a>
        </li>
        <li {{ selected('files') }}>
            <a href="{{url_for('app.files')}}" title=""><img src="{{url_for('static', filename='img/head-menu-development.png')}}" alt="" /> {{_("Files")}}</a>
        </li>
        <!-- <li {{ selected('filemanager') }}> -->
            <!-- <a href="/filemanager" title=""><img src="{{url_for('static', filename='img/head-menu-download.png')}}" alt="" /> {{_("File Manager")}}</a> -->
        <!-- </li> -->
        <li {{ selected('logs', True) }}>
            <a href="{{url_for('app.logs')}}"  class="action index" accesskey="x" rel="nofollow"><img src="{{url_for('static', filename='img/head-menu-index.png')}}" alt="" />{{_("Logs")}}</a>
        </li>
        <li {{ selected('settings', True) }}>
            <a href="{{url_for('app.settings')}}"  class="action index" accesskey="x" rel="nofollow"><img src="{{url_for('static', filename='img/head-menu-config.png')}}" alt="" />{{_("Settings")}}</a>
        </li>
        {% endblock %}

        </ul>
    </div>

    <div style="clear:both;"></div>
</div>

{% if perms.STATUS %}
<ul id="page-actions2">
    <li id="action_play"><a href="#"  class="action play" accesskey="o" rel="nofollow">{{_("Start")}}</a></li>
    <li id="action_stop"><a href="#"  class="action stop" accesskey="o" rel="nofollow">{{_("Stop")}}</a></li>
    <li id="action_cancel"><a href="#"  class="action cancel" accesskey="o" rel="nofollow">{{_("Cancel")}}</a></li>
    <li id="action_add"><a href="#"  class="action add" accesskey="o" rel="nofollow" >{{_("Add")}}</a></li>
</ul>
{% endif %}

{% if perms.LIST %}
<ul id="page-actions">
    <li><span class="time">{{_("Running:")}}</span><a id="time" style=" background-color: {% if status.download %}#8ffc25{% else %} #fc6e26{% endif %}; padding-left: 0cm; padding-right: 0.1cm; "> {% if status.download %}{{_("on")}}{% else %}{{_("off")}}{% endif %}</a></li>
    <li><span class="reconnect">{{_("Reconnect:")}}</span><a id="reconnect" style=" background-color: {% if status.reconnect %}#8ffc25{% else %} #fc6e26{% endif %}; padding-left: 0cm; padding-right: 0.1cm; "> {% if status.reconnect %}{{_("on")}}{% else %}{{_("off")}}{% endif %}</a></li>
    <li><a class="action backlink">{{_("Speed:")}} <b id="speed">{{ status.speed }}</b></a></li>
    <li><a class="action cog">{{_("Queue:")}} <b id="actives" title="{{_("Active")}}">{{ status.active }}</b> | <b id="actives_from" title="{{_("Queued")}}">{{ status.queue }}</b> | <b id="actives_total" title="{{_("Total")}}">{{ status.total }}</b></a></li>
    <li><a href=""  class="action revisions" accesskey="o" rel="nofollow">{{_("Reload page")}}</a></li>
</ul>
{% endif %}

{% block pageactions %}
{% endblock %}
<br/>

<div id="body-wrapper" class="dokuwiki">

<div id="content" lang="en" dir="ltr">

<h1>{% block subtitle %}pyLoad{% endblock %}</h1>

{% block error %}
{% endblock error %}

{% block statusbar %}
{% endblock %}

<br/>

<div class="level1" style="clear:both">
</div>
<noscript><h1>Enable JavaScript to use the webinterface.</h1></noscript>

<div id="load-indicator" style="opacity: 0; float: right; margin-top: -10px;">
    <img src="{{url_for('static', filename='img/ajax-loader.gif')}}" alt="" style="padding-right: 5px"/>
    {{_("loading")}}
</div>

{% block content %}
{% endblock content %}

    <hr style="clear: both;" />

<div id="foot">&copy; 2008-2025 pyLoad team
<a href="#" class="action top" accesskey="x"><span>{{_("Back to top")}}</span></a><br />
<!--<div class="breadcrumbs"></div>-->

</div>
</div>
</div>

<div style="display: none;">
    {% include 'window.html' %}
    {% include 'captcha.html' %}
    {% block hidden %}
    {% endblock %}
</div>

</body>
</html>

src/pyload/webui/app/templates/captcha.html
<!-- Captcha box -->
<div id="cap_box" class="window_box">
    <form id="cap_form" action="{{url_for('json.set_captcha')}}" method="POST" enctype="multipart/form-data" onsubmit="return false;">
        <h1>{{_("Captcha reading")}}</h1>
        <p id="cap_title">{{_("Please read the text on the captcha.")}}</p>

        <input id="cap_id" name="cap_id" type="hidden" value="" />
        <div id="cap_textual">
            <label>{{_("Captcha")}}
            <span class="small">{{_("The captcha.")}}</span>
            </label>
            <span class="cont">
                <img id="cap_textual_img" src="">
            </span>
            <label>{{_("Text")}}
            <span class="small">{{_("Input the text on the captcha.")}}</span>
            </label>
            <input id="cap_result" name="cap_result" type="text" size="20" />
        </div>

        <div id="cap_positional" style="display: none; text-align: center">
            <img id="cap_positional_img" src="" style="margin: 10px; cursor:pointer">
        </div>

        <div id="cap_interactive" style="display: none; text-align: center; padding-bottom: 15px;">
            <div id="cap_iframe_clipping" style="overflow: hidden;">
                <iframe src="" id="cap_interactive_iframe" sandbox="allow-scripts allow-forms allow-same-origin" style="position: relative; height: 100%; width: 100%; overflow: hidden; border: 0;">
                    <p>{{_('Your browser does not support iframes.')}}</p>
                </iframe>
            </div>
            <div id="cap_interactive_loading">
                <p style="white-space: nowrap;">{{_("The captcha may take a few seconds to load.")}}</p>
                <p>{{_("Note: to solve this interactive captchas")}}<br>
                {{_("Please install the <a href='https://tampermonkey.net/' target='_blank'>Tampermonkey</a> add-on in your browser and add the ")}}<a href="{{url_for('static', filename='js/captcha-interactive.user.js')}}">{{_("pyload userscript")}}</a>.</p>
            </div>
            <div id="cap_invisible_loading">
              <p style="white-space: nowrap;">{{_("Invisible captcha is in background progress,")}}</p><br>
              <p style="white-space: nowrap;">{{_("this window will automatically close, please wait.")}}</p><br>
              <p>{{_("Note: to solve this interactive captchas")}}<br>
                {{_("Please install the <a href='https://tampermonkey.net/' target='_blank'>Tampermonkey</a> add-on in your browser and add the ")}}<a href="{{url_for('static', filename='js/captcha-interactive.user.js')}}">{{_("pyload userscript")}}</a>.</p>
            </div>
        </div>

        <div id="button_bar" style="text-align: center">
            <span>
                <button id="cap_submit" type="submit" style="margin-left: 0">{{_("Submit")}}</button>
                <button id="cap_reset" type="reset" style="margin-left: 0">{{_("Close")}}</button>
            </span>
        </div>

        <div class="spacer"></div>

    </form>

</div>

src/pyload/webui/app/templates/dashboard.html
{% extends 'base.html' %} {% block head %}
<script
  type="text/javascript"
  src="{{theme_template('js/dashboard.js')}}"
></script>
{% endblock %} {% block subtitle %} {{_("Active Connections")}} {% endblock %}
{% block menu %}
<li class="selected">
  <a href="{{url_for('app.dashboard')}}" title=""
    ><img
      src="{{url_for('static', filename='img/head-menu-home.png')}}"
      alt=""
    />
    {{_("Dashboard")}}</a
  >
</li>
<li>
  <a href="{{url_for('app.queue')}}" title=""
    ><img
      src="{{url_for('static', filename='img/head-menu-queue.png')}}"
      alt=""
    />
    {{_("Queue")}}</a
  >
</li>
<li>
  <a href="{{url_for('app.collector')}}" title=""
    ><img
      src="{{url_for('static', filename='img/head-menu-collector.png')}}"
      alt=""
    />
    {{_("Packages")}}</a
  >
</li>
<li>
  <a href="{{url_for('app.files')}}" title=""
    ><img
      src="{{url_for('static', filename='img/head-menu-development.png')}}"
      alt=""
    />
    {{_("Files")}}</a
  >
</li>
<!-- <li> -->
<!-- <a href="/filemanager" title=""><img src="{{url_for('static', filename='img/head-menu-download.png')}}" alt="" /> {{_("File Manager")}}</a> -->
<!-- </li> -->
<li class="right">
  <a href="{{url_for('app.logs')}}" class="action index" accesskey="x" rel="nofollow"
    ><img
      src="{{url_for('static', filename='img/head-menu-index.png')}}"
      alt=""
    />{{_("Logs")}}</a
  >
</li>
<li class="right">
  <a href="{{url_for('app.settings')}}" class="action index" accesskey="x" rel="nofollow"
    ><img
      src="{{url_for('static', filename='img/head-menu-config.png')}}"
      alt=""
    />{{_("Settings")}}</a
  >
</li>
{% endblock %} {% block content %}
<table width="100%" class="queue">
  <thead>
    <tr class="header">
      <th>{{_("Name")}}</th>
      <th>{{_("Status")}}</th>
      <th>{{_("Info")}}</th>
      <th>{{_("Size")}}</th>
      <th>{{_("Progress")}}</th>
    </tr>
  </thead>
  <tbody id="LinksAktiv">
    {% for link in content %}
    <tr id="link_{{ link.id }}">
      <td id="link_{{ link.id }}_name">{{ link.name }}</td>
      <td id="link_{{ link.id }}_status">{{ link.status }}</td>
      <td id="link_{{ link.id }}_info">{{ link.info }}</td>
      <td id="link_{{ link.id }}_bleft">{{ link.format_size }}</td>
      <td>
        <span id="link_{{ link.id }}_percent"
          >{{ link.percent }}% /{{ link.bleft }}</span
        >
        <img
          id="link_{{ link.id }}_remove"
          style="
            vertical-align: middle;
            margin-right: -20px;
            margin-left: 5px;
            margin-top: -2px;
            cursor: pointer;
          "
          src="{{url_for('static', filename='img/control-cancel.png')}}"
        />
      </td>
    </tr>
    <tr id="link_{{ link.id }}_pgb_tr">
      <td colspan="5">
        <div
          id="link_{{ link.id }}_pgb"
          class="progressBar"
          style="background-color: green; height:4px; width: {{ link.percent }}%;"
        >
          &nbsp;
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

src/pyload/webui/app/templates/files.html
{% extends 'base.html' %}

{% block title %}{{_("Saved Files")}} - {{super()}} {% endblock %}

{% block subtitle %}
{{_("Saved Files")}}
{% endblock %}

{% block content %}

<ul>
    {% for folder in files.folder %}
    <li>
        {{ folder.name }}
        <ul>
        {% for file in folder.files %}
        <li><a href='files/get/{{ folder.path|escape }}/{{ file|escape }}'>{{file}}</a></li>
        {% endfor %}
        </ul>
    </li>
    {% endfor %}

    {% for file in files.files %}
    <li> <a href='files/get/{{ file|escape }}'>{{ file }}</a></li>
    {% endfor %}

</ul>

{% endblock %}

src/pyload/webui/app/templates/folder.html
<li class="folder">
  <input type="hidden" name="path" class="path" value="{{ path }}" />
  <input type="hidden" name="name" class="name" value="{{ name }}" />
  <span>
    <b>{{ name }}</b>
    <span class="buttons" style="opacity:0">
      <img title="{{_("Rename Directory")}}" class="rename" style="cursor: pointer" height="12px" src="{{url_for('static', filename='img/pencil.png')}}" />
      &nbsp;&nbsp;
      <img title="{{_("Delete Directory")}}" class="delete" style="margin-left: -10px; cursor: pointer" width="12px" height="12px" src="{{url_for('static', filename='img/delete.png')}}" />
      &nbsp;&nbsp;
      <img title="{{_("Add subdirectory")}}" class="mkdir" style="margin-left: -10px; cursor: pointer" width="12px" height="12px" src="{{url_for('static', filename='img/add_folder.png')}}" />
    </span>
  </span>
  <div style="display:none">{{ _("Folder is empty") }}</div>
</li>

src/pyload/webui/app/templates/login.html
{% extends 'base.html' %}
{% set no_status_polling = 1 %}

{% block title %}{{_("Login")}} - {{super()}} {% endblock %}

{% block content %}

<div class="centeralign">
<form action="" method="post" accept-charset="utf-8" id="login">
    <div class="no">
        <input type="hidden" name="do" value="login" />
        <fieldset>
        <legend>Login</legend>
        <label>
            <span>{{_("Username")}}</span>
            <input type="text" size="20" name="username" />
        </label>
        <br />
        <label>
            <span>{{_("Password")}}</span>
            <input type="password" size="20" name="password" />
        </label>
        <br />
        <input type="submit" value="Login" class="button" />
        </fieldset>
    </div>
</form>

{% if errors %}
<p>{{_("Your username and password didn't match. Please try again.")}}</p>
  {{ _("To reset default admin login run:") }} <b>pyload -r</b>
{% endif %}

</div>
<br>

{% endblock %}

src/pyload/webui/app/templates/logout.html
{% extends 'base.html' %}
{% set no_status_polling = 1 %}

{% block head %}
<meta http-equiv="refresh" content='3; url="{{url_for('app.dashboard')}}"'>
{% endblock %}

{% block content %}
<p><b>{{_("You were successfully logged out.")}}</b></p>
{% endblock %}